### ISSUE TITLE
Add flag how to handle unknown enum values.

### ISSUE THREAD

**Issue by stephanschnabel** [kokuwaio/micronaut-openapi-codegen#14]
Currently all unknown Enum values are rejected with `IllegalArgumentException`.

Add an config option **enumHandling**:
 * **reject**: throw `IllegalArgumentException` (default)
 * **optional**: method with `JsonCreator` returns optional
 * **string**: use string instead of enums

**Comment by wistefan** [comment]
"Currently all unknown Enum values are rejected with IllegalArgumentException." 
Thats not always the case. If you set the config to useReferencedSchemaAsDefault=true, a default enum will be created.

**Comment by stephanschnabel** [comment]
ok, closed.
