### ISSUE TITLE
Missing support for default response

### ISSUE THREAD

**Issue by mhartmann-jaconi** [kokuwaio/micronaut-openapi-codegen#214]
When generating API files for an openapi spec, which contains "default" responses, the generator fails, as this feature seems not to be supported through https://github.com/kokuwaio/micronaut-openapi-codegen/blob/main/src/main/java/org/openapitools/codegen/languages/MicronautCodegen.java#L265 .

The ask would be, if we can enable this, as it is part of the openapi specification and should therefore be supported.

**Comment by sschnabe** [comment]
Please take a look at #216

**Comment by sschnabe** [comment]
Fixed with [3.2.2](https://github.com/kokuwaio/micronaut-openapi-codegen/releases/tag/3.2.2)
