### ISSUE TITLE
Invalid filename for default class with modelNameSuffix

### ISSUE THREAD

**Issue by infomouse** [kokuwaio/micronaut-openapi-codegen#318]
Steps to reproduce:
1. Set modelNameSuffix (ex. Dto).
2. Generate code for model used in allOf.
3. Get interface ModelDto and default class ModelDtoDefault in file ModelDefaultDto.

codegen version: 4.0.2
gradle openapi generator: 7.0.1

source: https://github.com/infomouse/micronaut-openapi-codegen-test

**Comment by sschnabe** [comment]
@infomouse can you review the pull request #319 ?

**Comment by sschnabe** [comment]
And thanks for the excellent bug report!
