### ISSUE TITLE
Errors in Map implementation

### ISSUE THREAD

**Issue by pulledtim** [kokuwaio/micronaut-openapi-codegen#328]
The way that Maps are generated at the moment has two issues:
- Equals [calls super.equal](https://github.com/kokuwaio/micronaut-openapi-codegen/blob/075d7dedbd289dbe93ca3a45a8856019ca6174f7/gen/main/java/issue/_315/ServiceScopes.java#L22) without having a parent, which makes checks fail
- serialization adds "additionalProperties" as a field, leading to having an additional entry in the deserialized resulting map (key=additionalProperties, value=null) due to the @JsonAnySetter annotated method

Will provide PR with updated generated models as a suggestion

**Comment by pulledtim** [comment]
After discussing with @wistefan I rechecked the second issue and found out that the problem only occures with the ObjectMapper created by Micronaut(io.micronaut.jackson.ObjectMapperFactory) with the default config and not when using a plain ObjectMapper. Will reduce the PR to only address point 1

**Comment by sschnabe** [comment]
@pulledtim  Is this still relevant?
