### ISSUE TITLE
OpenAPI file upload generates incorrect Api interface.

### ISSUE THREAD

**Issue by TrisTronNL** [kokuwaio/micronaut-openapi-codegen#35]
Operation with a file upload generates incorrect Api interface.

openapi.yaml
```
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
```

see http://spec.openapis.org/oas/v3.0.3#considerations-for-file-uploads

Generated interface:
`Object someOperation(@io.micronaut.http.annotation.Body File body);`

The param should be of type byte[].

I hope this can get fixed because we need this in an application we're developing.
Thanks!

**Comment by TrisTronNL** [comment]
Or even better StreamingFileUpload, but I think this requires multipart/form-data.

**Comment by stephanschnabel** [comment]
I cannot reproduce this issue, see [07e94de](https://github.com/kokuwaio/micronaut-openapi-codegen/commit/07e94de0ca7957091853bf57235e845e72d8ab15). Which version of this codegen did you used?

**Comment by stephanschnabel** [comment]
I've implemented fileupload. Is this sufficient for your usecase?

**Comment by TrisTronNL** [comment]
Hi, thanks for the reply & fix! The MediatypeController.mediatypePostMultipart example is exactly what I was looking for. I'll test it next week with our openapi.yaml. Thanks again.

**Comment by stephanschnabel** [comment]
Please try version [1.6.3](https://repo1.maven.org/maven2/io/kokuwa/micronaut/micronaut-openapi-codegen/1.6.3/).
