### ISSUE TITLE
Missing property "removeEnumValuePrefix" in AdditionalProperties

### ISSUE THREAD

**Issue by AleksandrMishinn** [kokuwaio/micronaut-openapi-codegen#363]
Hey, guys!
I faced with an issue that property "removeEnumValuePrefix" doesn't work.
I use it like this:

`tasks.register("generateSomeServer", CommonGenerateTask::class) {
   ...
    with(additionalProperties) {
        put("removeEnumValuePrefix", "false")
    }
}`

But it doesn't work :(

**Comment by AleksandrMishinn** [comment]
My fix suggestion - https://github.com/kokuwaio/micronaut-openapi-codegen/pull/364

**Comment by sschnabe** [comment]
#364 was closed by dependabot because he deleted his branch. I've created #370 but was not able to merge it because of conflicts. With #371 this problem should be solved.
