### ISSUE TITLE
Query params naming

### ISSUE THREAD

**Issue by AleksandrMishinn** [kokuwaio/micronaut-openapi-codegen#366]
Hey, guys!

I've encountered a behavior where the names of the query parameters don't match the names in the specification. Could you tell me, is this how it should work or is it a bug?

This specification param
![image](https://github.com/kokuwaio/micronaut-openapi-codegen/assets/51471511/de75e704-6803-4e82-92a9-f96635bbc25d)

generates this code
![image](https://github.com/kokuwaio/micronaut-openapi-codegen/assets/51471511/2d8b53ee-c037-4ad2-b2dc-0b3de3420aec)

If "name" is "my_query_param" why I have "myQueryParam" in generated code? It makes me add @QueryParam("my_query_param") everywhere in code ;(

**Comment by sschnabe** [comment]
I'm busy right now. I got this an will response end of this week.

**Comment by AleksandrMishinn** [comment]
Ok. Thank you for reply
