### ISSUE TITLE
Generator does not honor "modelNamePrefix" setting of OpenApi Maven plugin

### ISSUE THREAD

**Issue by jfiedler-jaconi** [kokuwaio/micronaut-openapi-codegen#414]
The Kokuwa generator does not seem to support the common "modelNamePrefix" parameter of the openapi-generator-maven-plugin. The generated model classes do not have the configured prefix. This was working in the past (used very old version 2.3.0 before).

OpenApi Maven Plugin: 7.4.0
Kokuwa Version: 4.2.0

**Comment by sschnabe** [comment]
Fixed with #415 , can you verify that this pr resolves your issue?
