### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by volkerrichert** [kokuwaio/micronaut-openapi-codegen#42]
Hi!

I'd like to use this code gen using NODE openapi tools cli. But i can't find an hint how to use it.

TNX
Volker

**Comment by stephanschnabel** [comment]
Just for my clarification: you want to generate Micronaut Java APIs with [@openapitools/openapi-generator-cli](https://www.npmjs.com/package/@openapitools/openapi-generator-cli)?

**Comment by stephanschnabel** [comment]
No response.
