### ISSUE TITLE
Too many brackets 

### ISSUE THREAD

**Issue by Sotec-IoT** [kokuwaio/micronaut-openapi-codegen#87]
Setup:
```
openApiGenerate {
	generatorName = "micronaut"
	inputSpec = "${rootDir}/****/api.yaml"
	outputDir = "${buildDir}/HTTP"
	apiPackage = "com.***.api"
	invokerPackage = "com.***.invoker"
	modelPackage = "com.***.model"
	generateApiTests = true
	generateModelTests = false
	configOptions = [
			useGenericResponse     : "true",
			useOptionals           : "false",
			dateTimeRelaxed        : "false",
			fullJavaUtil           : "true",
			jacksonDatabindNullable: "false",
			supportAsync           : "false"
	]
}
```

Expected:
- generate endpoints with micronaut http responses

Observed:
- httpResponses have additional brackets, see: 
![image](https://user-images.githubusercontent.com/32332583/153227524-44a57cb4-5bd6-488d-b5e1-41843d02c06e.png)

**Comment by sschnabe** [comment]
This is generated code. The use of brackets is not wrong there. 

If you need to fix this because of you style guide please provide a pr.
